services:

  postgres:
    image: postgres:15-alpine
    container_name: juju_transfer_postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: juju_transfer
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data_juju_transfer:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD", "pg_isready", "-U", "${POSTGRESQL_USERNAME}" ]
      interval: 10s
      timeout: 5s
      retries: 5

  minio:
    image: minio/minio:latest
    container_name: juju_transfer_minio
#    ports:
#      - "9000:9000"
#      - "9001:9001"
    labels:
        # MinIO API
      - traefik.http.routers.minio.rule=Host(`s3.localhost`)
      - traefik.http.routers.minio.service=minio
      - traefik.http.services.minio.loadbalancer.server.port=9000
      - traefik.http.routers.minio.entrypoints=http

      # MinIO Console
      - traefik.http.routers.console.rule=Host(`consoles3.localhost`)
      - traefik.http.routers.console.service=console
      - traefik.http.services.console.loadbalancer.server.port=9001
      - traefik.http.routers.console.entrypoints=https
      - traefik.http.routers.console.tls=true
    volumes:
      - minio-data:/data
      - ./minio.env:/etc/minio/minio.env:ro
    environment:
      - MINIO_CONFIG_ENV_FILE=/etc/minio/minio.env
    command: server /data --console-address ":9001"
    restart: unless-stopped
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:9000/minio/health/live" ]
      interval: 10s
      timeout: 5s
      retries: 5

  reverse_proxy:
    image: traefik
    command:
      - --providers.swarm
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./traefik/ssl:/etc/traefik/certificates
      - ./traefik/traefik.yaml:/etc/traefik/traefik.yaml
    ports:
      - "80:80" # Web sites
      - "443:443" # Web sites
      - "8080:8080" # Traefik dashboard
      - "9000:9000" # MinIO API
      - "9001:9001" # MinIO Console

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    labels:
      - traefik.http.routers.backend.rule=Host("localhost") && PathPrefix("/api")
      - traefik.http.routers.backend.entrypoints=https
      - traefik.http.routers.backend.tls=true
      - traefik.http.services.backend.loadbalancer.sticky=true
      - traefik.http.services.backend.loadbalancer.sticky.cookie.name=StickyCookie
      - traefik.http.services.backend.loadbalancer.sticky.cookie.secure=true
      - traefik.http.services.backend.loadbalancer.sticky.cookie.samesite=strict
    extra_hosts:
      - "s3.localhost:172.19.0.5"
    env_file:
      - .env
    deploy:
      replicas: 1
    depends_on:
      postgres:
        condition: service_healthy
      minio:
        condition: service_healthy

  frontend:
    build:
      context: ../jujuTransfer-Frontend
      dockerfile: Dockerfile
    labels:
      - traefik.http.routers.frontend.rule=Host("localhost")
      - traefik.http.routers.frontend.entrypoints=https
      - traefik.http.routers.frontend.tls=true
    deploy:
      replicas: 1
    environment:
      - REACT_APP_API_URL=${REACT_APP_API_URL}

volumes:
  postgres_data_juju_transfer:
  minio-data: