services:
  # PostgreSQL Database
  postgres:
    image: postgres:15-alpine
    container_name: juju_transfer_postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: juju_transfer
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data_juju_transfer:/var/lib/postgresql/data
    networks:
      - network_juju_transfer

volumes:
  postgres_data_juju_transfer:

networks:
  network_juju_transfer:
    driver: bridge